### ISSUE TITLE
Doubt: where to put firefox config

### ISSUE THREAD

**Issue by luispengler** [sanchit-sehgal/dotfiles-v2#1]
Hey, sorry for asking, this is not actually an issue I found.
I would just like to know where I can put the file under /firefox which is "treestyletab.css" and make it work in my installation.

**Comment by sanchit-sehgal** [comment]
in your firefox config **(/.mozilla/firefox/random string of letters that make no sense.default-release/)** you need to make a folder called chrome. Add the chrome folder from this repository (it's in firefox/chrome) to that chrome folder. Then, you need to open firefox and go to **toolkit.legacyUserProfileCustomizations.stylesheets** and set it to true. Restart chrome and you should find that your top panel looks like mine. 

The **treestyletab.css** file is the one that styles my vertical tabs as shown in the screenshots. To use those, you would have to install an extension called _Tab Center Reborn_. Go to preferences and set the following:

    - Animations: on.
    - Use current browser theme: on, if you want to use dark mode.
    - Compact Mode: either “Dynamic” or “Enabled”. It works with “Disabled” too but looks nicer with only favicons.
    - Favicon-only pinned tabs: off.
    - Activate Custom Stylesheet and paste the contents of treestyletab.css into the text area below, and click “Save CSS” under the textbox. 
  
Adjust the colors as necessary and your firefox should look just like mine! Create another issue/respond to this one if you still have any issues that I can help you with.

**Comment by sanchit-sehgal** [comment]
Oops, didn't mean to close the issue lol.

**Comment by luispengler** [comment]
Sorry for the late reply, but thank you so much!

**Comment by sanchit-sehgal** [comment]
No problem! Closing this issue now- create another one if you have any more questions!
