### ISSUE TITLE
Missing private-build-plans.toml for the Iosevka Custom font

### ISSUE THREAD

**Issue by paulcsiki** [sanchit-sehgal/dotfiles-v2#2]
Please add the toml file to reconstruct the custom font.

**Comment by sanchit-sehgal** [comment]
Custom Font has been replaced. SauceCodePro is now the font for the system. Iosevka Custom proved to be unreliable and corrupted for some reason. Sorry!

**Comment by paulcsiki** [comment]
Thanks.
